require("../css/reset.css");
require("../css/swiper-3.4.1.min.css");
require("../css/index.css");
require("../css/common.css");
require("../css/unslider.css");
require("../css/unslider-dots.css");
require("../css/collection.css");
require("../css/museum.css");
require("../css/digitization.css");
require("../css/display.css");
require("../css/login.css");
require('../css/album.css');
var app=require("./app");
var controllr=require("./controllers");
var directive=require("./directives");
var filter=require("./fliters");
var router=require("./router");
var services=require("./services");